[theme]
# Force light theme always
base = "light"
primaryColor = "#ff6b6b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[server]
# Optional: Set server configuration
enableCORS = false
enableXsrfProtection = false 